# Generated by Django 5.2.13 on 2026-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
