# Generated by Django 5.2.13 on 2026-05-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]

