# Generated by Django 5.2.13 on 2026-05-27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bookreview_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["last_name", "first_name", "id"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["id"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterModelOptions(
            name="bookauthor",
            options={
                "ordering": ["id"],
                "verbose_name": "Book author relation",
                "verbose_name_plural": "Book author relations",
            },
        ),
        migrations.AlterModelOptions(
            name="bookreview",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Book review",
                "verbose_name_plural": "Book reviews",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="bookauthor",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_authors",
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="bookauthor",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_authors",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="stars_given",
            field=models.IntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookauthor",
            constraint=models.UniqueConstraint(fields=("book", "author"), name="unique_book_author_relation"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["last_name", "first_name"], name="books_autho_last_na_95ebd0_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_book_title_9d0fd7_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="books_book_isbn_d7f35b_idx"),
        ),
        migrations.AddIndex(
            model_name="bookauthor",
            index=models.Index(fields=["book", "author"], name="books_booka_book_id_7c9612_idx"),
        ),
        migrations.AddIndex(
            model_name="bookauthor",
            index=models.Index(fields=["author", "book"], name="books_booka_author__44d504_idx"),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(fields=["book", "-created_at"], name="books_bookr_book_id_29073f_idx"),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(fields=["user", "-created_at"], name="books_bookr_user_id_a7c82e_idx"),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(fields=["book", "stars_given"], name="books_bookr_book_id_5f2b16_idx"),
        ),
    ]

