# Generated by Django 5.2.13 on 2026-05-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_database_optimizations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='author',
            new_name='books_autho_last_na_7ca250_idx',
            old_name='books_autho_last_na_95ebd0_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_title_d3218d_idx',
            old_name='books_book_title_9d0fd7_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_isbn_54becd_idx',
            old_name='books_book_isbn_d7f35b_idx',
        ),
        migrations.RenameIndex(
            model_name='bookauthor',
            new_name='books_booka_book_id_4f4f55_idx',
            old_name='books_booka_book_id_7c9612_idx',
        ),
        migrations.RenameIndex(
            model_name='bookauthor',
            new_name='books_booka_author__d8e270_idx',
            old_name='books_booka_author__44d504_idx',
        ),
        migrations.RenameIndex(
            model_name='bookreview',
            new_name='books_bookr_book_id_4a01df_idx',
            old_name='books_bookr_book_id_29073f_idx',
        ),
        migrations.RenameIndex(
            model_name='bookreview',
            new_name='books_bookr_user_id_87ebf2_idx',
            old_name='books_bookr_user_id_a7c82e_idx',
        ),
        migrations.RenameIndex(
            model_name='bookreview',
            new_name='books_bookr_book_id_5f5699_idx',
            old_name='books_bookr_book_id_5f2b16_idx',
        ),
    ]
