# Generated by Django 5.2.13 on 2026-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_books_autho_last_na_95ebd0_idx_books_autho_last_na_7ca250_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
