# Generated by Django 5.2.13 on 2026-05-27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_book_cover_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorited_by", to="books.book"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="books_favor_user_id_bf5172_idx"),
                    models.Index(fields=["book", "-created_at"], name="books_favor_book_id_911ca8_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("user", "book"), name="unique_user_book_favorite")],
            },
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("want_to_read", "Want to read"), ("reading", "Reading"), ("finished", "Finished")],
                        db_index=True,
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_entries",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading list entry",
                "verbose_name_plural": "Reading list entries",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="books_readi_user_id_b9c72b_idx"),
                    models.Index(fields=["book", "status"], name="books_readi_book_id_85250e_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("user", "book"), name="unique_user_book_reading_list")],
            },
        ),
    ]

