# Generated by Django 5.2.13 on 2026-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_favorite_readinglist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='books_favor_user_id_feb3d3_idx',
            old_name='books_favor_user_id_bf5172_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='books_favor_book_id_fbbed3_idx',
            old_name='books_favor_book_id_911ca8_idx',
        ),
        migrations.RenameIndex(
            model_name='readinglist',
            new_name='books_readi_user_id_8c9a22_idx',
            old_name='books_readi_user_id_b9c72b_idx',
        ),
        migrations.RenameIndex(
            model_name='readinglist',
            new_name='books_readi_book_id_165e7f_idx',
            old_name='books_readi_book_id_85250e_idx',
        ),
    ]
