# Generated by Django 5.2.13 on 2026-05-27 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_books_favor_user_id_bf5172_idx_books_favor_user_id_feb3d3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='readinglist',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_book_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='readinglist',
            name='unique_user_book_reading_list',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='books_favor_user_id_feb3d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='books_favor_book_id_fbbed3_idx',
        ),
        migrations.RemoveIndex(
            model_name='readinglist',
            name='books_readi_user_id_8c9a22_idx',
        ),
        migrations.RemoveIndex(
            model_name='readinglist',
            name='books_readi_book_id_165e7f_idx',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.book'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to='books.book'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('finished', 'Finished'), ('planned', 'Planned')], default='reading', max_length=20),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('user', 'book')},
        ),
    ]
